language: go
sudo: false
go:
  - 1.8.x
  - tip

before_install:
  - go get -t -v ./...

install:
  - go get code.google.com/p/go.tools/cmd/cover
  - go get github.com/mattn/goveralls
script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

