language: go
sudo: false
go:
  - 1.8.x
  - tip

before_install:
  - go get -t -v ./...

install:
  - go get code.google.com/p/go.tools/cmd/cover
  - go get github.com/mattn/goveralls
script:
<<<<<<< HEAD
  - go test -v -covermode=count -coverprofile=coverage.out
  - $(go env GOPATH | awk 'BEGIN{FS=":"} {print $1}')/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
env:
  secure: <need to generate this>
=======
  - go test -race -coverprofile=coverage.txt -covermode=atomic

>>>>>>> dev
